// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz2zHTxPNEGjD6LPVjo8cGA-tI18JDOxg',
    appId: '1:372541546387:web:93ab9258f056d06fe3d266',
    messagingSenderId: '372541546387',
    projectId: 'iot-inventory-management-7c555',
    authDomain: 'iot-inventory-management-7c555.firebaseapp.com',
    storageBucket: 'iot-inventory-management-7c555.firebasestorage.app',
    measurementId: 'G-QVS5CMLRV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATSQg3vQSU3SEprmQc6aI6fPrur6c5paY',
    appId: '1:372541546387:android:f356d3db96b0c8a9e3d266',
    messagingSenderId: '372541546387',
    projectId: 'iot-inventory-management-7c555',
    storageBucket: 'iot-inventory-management-7c555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm9zy-D3JxzHuIexwAbl_uVEaepR0Wkjc',
    appId: '1:372541546387:ios:07caf672c5f79a32e3d266',
    messagingSenderId: '372541546387',
    projectId: 'iot-inventory-management-7c555',
    storageBucket: 'iot-inventory-management-7c555.firebasestorage.app',
    iosBundleId: 'com.example.capstoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm9zy-D3JxzHuIexwAbl_uVEaepR0Wkjc',
    appId: '1:372541546387:ios:07caf672c5f79a32e3d266',
    messagingSenderId: '372541546387',
    projectId: 'iot-inventory-management-7c555',
    storageBucket: 'iot-inventory-management-7c555.firebasestorage.app',
    iosBundleId: 'com.example.capstoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz2zHTxPNEGjD6LPVjo8cGA-tI18JDOxg',
    appId: '1:372541546387:web:625c85cb7e70b1fde3d266',
    messagingSenderId: '372541546387',
    projectId: 'iot-inventory-management-7c555',
    authDomain: 'iot-inventory-management-7c555.firebaseapp.com',
    storageBucket: 'iot-inventory-management-7c555.firebasestorage.app',
    measurementId: 'G-LLJC8YL69R',
  );
}
