// lib/widgets/add_food_dialog.dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import '../models/food_item.dart';
import '../providers/food_tracker_state.dart';
import '../utils/emoji_picker.dart'; // <-- Import our new helper

class AddFoodDialog extends StatefulWidget {
  const AddFoodDialog({super.key});

  @override
  State<AddFoodDialog> createState() => _AddFoodDialogState();
}

class _AddFoodDialogState extends State<AddFoodDialog> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _quantityController = TextEditingController();
  String _selectedCategory = 'vegetables'; // Default category

  bool _isAdding = false;

  // Define the category list
  final List<String> _categories = [
    'vegetables',
    'fruit',
    'meat',
    'dairy',
    'packaged',
    'drinks',
    'condiments',
    'others'
  ];

  Future<void> _submitForm() async {
    if (_formKey.currentState!.validate()) {
      setState(() => _isAdding = true);

      final quantity = int.tryParse(_quantityController.text) ?? 0;
      final name = _nameController.text;

      // Create a new FoodItem based on your new schema
      final newItem = FoodItem(
        id: '', // Will be generated by PocketBase
        name: name,
        category: _selectedCategory,
        quantity: quantity,
        lastDetected: DateTime.now(),
        // --- EMOJI LOGIC ---
        // Compute the icon for the manually added item
        icon: EmojiPicker.getEmojiForItem(name, _selectedCategory),
      );

      await context.read<FoodTrackerState>().addItem(newItem);

      if (mounted) {
        setState(() => _isAdding = false);
        Navigator.pop(context);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      title: const Text('Add Food Item'),
      content: Form(
        key: _formKey,
        child: SizedBox(
          width: 300,
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                TextFormField(
                  controller: _nameController,
                  decoration: const InputDecoration(labelText: 'Item Name'),
                  validator: (value) =>
                      value == null || value.isEmpty ? 'Enter a name' : null,
                ),
                TextFormField(
                  controller: _quantityController,
                  decoration: const InputDecoration(labelText: 'Quantity'),
                  keyboardType: TextInputType.number,
                  inputFormatters: <TextInputFormatter>[
                    FilteringTextInputFormatter.digitsOnly
                  ],
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Enter a quantity';
                    }
                    if (int.tryParse(value) == null) {
                      return 'Enter a valid number';
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 10),
                DropdownButtonFormField<String>(
                  value: _selectedCategory,
                  // --- CATEGORY LIST ---
                  // Build items from our category list
                  items: _categories.map((category) {
                    // Capitalize first letter for display
                    String displayText =
                        category[0].toUpperCase() + category.substring(1);
                    return DropdownMenuItem(
                      value: category,
                      child: Text(displayText),
                    );
                  }).toList(),
                  onChanged: (val) => setState(() => _selectedCategory = val!),
                  decoration: const InputDecoration(labelText: 'Category'),
                ),
              ],
            ),
          ),
        ),
      ),
      actions: [
        TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel')),
        ElevatedButton(
          onPressed: _isAdding ? null : _submitForm,
          child: _isAdding
              ? const SizedBox(
                  width: 20,
                  height: 20,
                  child: CircularProgressIndicator(strokeWidth: 2),
                )
              : const Text('Add'),
        ),
      ],
    );
  }
}